export const CharactersData = [
  {
    id: "1",
    name: "Jonathan Joestar",
    animeDebut: 1,
    image: "https://jojos-bizarre-api.netlify.app/assets/jonathan.webp",
    nationality: "British",
    chapter: "Phantom Blood",
    living: false,
    isHuman: true,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "2",
    name: "Dio Brando",
    animeDebut: 1,
    image: "https://jojos-bizarre-api.netlify.app/assets/dio.webp",
    nationality: "British",
    chapter: "Phantom Blood",
    living: false,
    isHuman: false,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "3",
    name: "Erina Pendleton",
    animeDebut: 1,
    image: "https://jojos-bizarre-api.netlify.app/assets/erina.png",
    nationality: "British",
    chapter: "Phantom Blood",
    living: false,
    isHuman: true,
    isStandUser: false,
    gender: "female",
  },
  {
    id: "4",
    name: "Will Anthonio Zeppeli",
    animeDebut: 4,
    image: "https://jojos-bizarre-api.netlify.app/assets/zeppeli.webp",
    nationality: "Italian",
    chapter: "Phantom Blood",
    living: false,
    isHuman: true,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "5",
    name: "Robert E. O. Speedwagon",
    animeDebut: 2,
    image: "https://jojos-bizarre-api.netlify.app/assets/speedwagon.png",
    nationality: "English",
    chapter: "Phantom Blood",
    living: false,
    isHuman: true,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "6",
    name: "Tarkus",
    animeDebut: 5,
    image: "https://jojos-bizarre-api.netlify.app/assets/tarkus.webp",
    nationality: "British",
    chapter: "Phantom Blood",
    living: false,
    isHuman: false,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "7",
    name: "Bruford",
    animeDebut: 5,
    image: "https://jojos-bizarre-api.netlify.app/assets/bruford.webp",
    nationality: "Scottish",
    chapter: "Phantom Blood",
    living: false,
    isHuman: false,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "8",
    name: "Straizo",
    animeDebut: 7,
    image: "https://jojos-bizarre-api.netlify.app/assets/straizo.webp",
    nationality: "Tibetan",
    chapter: "Phantom Blood",
    living: false,
    isHuman: false,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "9",
    name: "Dire",
    animeDebut: 7,
    image: "https://jojos-bizarre-api.netlify.app/assets/dire.png",
    nationality: "Unknown",
    chapter: "Phantom Blood",
    living: false,
    isHuman: true,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "10",
    name: "Joseph Joestar",
    animeDebut: 10,
    image: "https://jojos-bizarre-api.netlify.app/assets/joseph.webp",
    nationality: "British",
    chapter: "Battle Tendency",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "11",
    name: "Caesar Anthonoio Zeppeli",
    animeDebut: 14,
    image: "https://jojos-bizarre-api.netlify.app/assets/caesar.png",
    nationality: "Italian",
    chapter: "Battle Tendency",
    living: false,
    isHuman: true,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "12",
    name: "Lisa Lisa",
    animeDebut: 16,
    image: "https://jojos-bizarre-api.netlify.app/assets/lisalisa.webp",
    nationality: "Italian",
    chapter: "Phantom Blood",
    living: false,
    isHuman: true,
    isStandUser: false,
    gender: "female",
  },
  {
    id: "13",
    name: "Rudol von Stroheim",
    animeDebut: 11,
    image: "https://jojos-bizarre-api.netlify.app/assets/stronheim.png",
    nationality: "German",
    chapter: "Battle Tendency",
    living: false,
    isHuman: false,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "14",
    name: "Kars",
    animeDebut: 14,
    image: "https://jojos-bizarre-api.netlify.app/assets/kars.webp",
    nationality: "Pillar Man",
    chapter: "Battle Tendency",
    living: false,
    isHuman: false,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "15",
    name: "Esidisi",
    animeDebut: 14,
    image: "https://jojos-bizarre-api.netlify.app/assets/esidisi.webp",
    nationality: "Pillar Man",
    chapter: "Battle Tendency",
    living: false,
    isHuman: false,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "16",
    name: "Wamuu",
    animeDebut: 14,
    image: "https://jojos-bizarre-api.netlify.app/assets/wamuu.webp",
    nationality: "Pillar Man",
    chapter: "Battle Tendency",
    living: false,
    isHuman: false,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "17",
    name: "Santana",
    animeDebut: 12,
    image: "https://jojos-bizarre-api.netlify.app/assets/santana.png",
    nationality: "Pillar Man",
    chapter: "Battle Tendency",
    living: false,
    isHuman: false,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "18",
    name: "Jotaro Kujo",
    animeDebut: 27,
    image: "https://jojos-bizarre-api.netlify.app/assets/jotaro.png",
    nationality: "Japanese",
    chapter: "Stardust Crusaders",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "19",
    name: "Muhammad Avdol",
    animeDebut: 27,
    image: "https://jojos-bizarre-api.netlify.app/assets/avdol.webp",
    nationality: "Egyptian",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "20",
    name: "Noriaki Kakyoin",
    animeDebut: 28,
    image: "https://jojos-bizarre-api.netlify.app/assets/kakyoin.webp",
    nationality: "Japanese",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "21",
    name: "Jean Pierre Polnareff",
    animeDebut: 30,
    image: "https://jojos-bizarre-api.netlify.app/assets/polnareff.png",
    nationality: "French",
    chapter: "Stardust Crusaders",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "22",
    name: "Iggy",
    animeDebut: 50,
    image: "https://jojos-bizarre-api.netlify.app/assets/iggy.webp",
    nationality: "American",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: false,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "23",
    name: "Enya the Hag",
    animeDebut: 28,
    image: "https://jojos-bizarre-api.netlify.app/assets/enya.webp",
    nationality: "Unknown",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "female",
  },
  {
    id: "24",
    name: "Vanilla Ice (Cool Ice)",
    animeDebut: 68,
    image: "https://jojos-bizarre-api.netlify.app/assets/vanillaice.png",
    nationality: "Unknown",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: false,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "25",
    name: "Hol Horse",
    animeDebut: 36,
    image: "https://jojos-bizarre-api.netlify.app/assets/holhorse.png",
    nationality: "Unknown",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "26",
    name: "J.Geil",
    animeDebut: 36,
    image: "https://jojos-bizarre-api.netlify.app/assets/geil.webp",
    nationality: "Unknown",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "27",
    name: "Daniel J. D'Arby",
    animeDebut: 60,
    image: "https://jojos-bizarre-api.netlify.app/assets/danieldarby.webp",
    nationality: "American",
    chapter: "Stardust Crusaders",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "28",
    name: "Terence T. D'Arby",
    animeDebut: 65,
    image: "https://jojos-bizarre-api.netlify.app/assets/terencedarby.png",
    nationality: "American",
    chapter: "Stardust Crusaders",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "29",
    name: "Pet Shop",
    animeDebut: 29,
    image: "https://jojos-bizarre-api.netlify.app/assets/petshop.png",
    nationality: "Unknown",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: false,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "30",
    name: "N'Doul",
    animeDebut: 51,
    image: "https://jojos-bizarre-api.netlify.app/assets/ndoul.png",
    nationality: "Egyptian",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "31",
    name: "Mariah",
    animeDebut: 55,
    image: "https://jojos-bizarre-api.netlify.app/assets/mariah.webp",
    nationality: "unknown",
    chapter: "Stardust Crusaders",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "female",
  },
  {
    id: "32",
    name: "Alessi",
    animeDebut: 57,
    image: "https://jojos-bizarre-api.netlify.app/assets/alessi.webp",
    nationality: "unknown",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "33",
    name: "Oingo (Zenyatta)",
    animeDebut: 52,
    image: "https://jojos-bizarre-api.netlify.app/assets/oingo.png",
    nationality: "Egyptian",
    chapter: "Stardust Crusaders",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "34",
    name: "Boingo (Mondatta)",
    animeDebut: 52,
    image: "https://jojos-bizarre-api.netlify.app/assets/boingo.png",
    nationality: "Egyptian",
    chapter: "Stardust Crusaders",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "35",
    name: "Anubis",
    animeDebut: 54,
    image: "https://jojos-bizarre-api.netlify.app/assets/anubis.png",
    nationality: "unknown",
    chapter: "Stardust Crusaders",
    living: true,
    isHuman: false,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "36",
    name: "Gray Fly",
    animeDebut: 30,
    image: "https://jojos-bizarre-api.netlify.app/assets/grayfly.png",
    nationality: "unknown",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "37",
    name: "Imposter Captain Tennille",
    animeDebut: 32,
    image: "https://jojos-bizarre-api.netlify.app/assets/captain.png",
    nationality: "unknown",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "38",
    name: "Forever",
    animeDebut: 33,
    image: "https://jojos-bizarre-api.netlify.app/assets/forever.png",
    nationality: "unknown",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: false,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "39",
    name: "Devo the Cursed",
    animeDebut: 34,
    image: "https://jojos-bizarre-api.netlify.app/assets/devo.webp",
    nationality: "Native American",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "40",
    name: "Rubber Soul",
    animeDebut: 35,
    image: "https://jojos-bizarre-api.netlify.app/assets/rubbersoul.png",
    nationality: "unknown",
    chapter: "Stardust Crusaders",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "41",
    name: "Nena",
    animeDebut: 38,
    image: "https://jojos-bizarre-api.netlify.app/assets/nena.webp",
    nationality: "unknown",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "female",
  },
  {
    id: "42",
    name: "ZZ",
    animeDebut: 39,
    image: "https://jojos-bizarre-api.netlify.app/assets/zz.webp",
    nationality: "unknown",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "43",
    name: "Steely Dan",
    animeDebut: 42,
    image: "https://jojos-bizarre-api.netlify.app/assets/steelydan.png",
    nationality: "unknown",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "44",
    name: "Arabia Fats",
    animeDebut: 44,
    image: "https://jojos-bizarre-api.netlify.app/assets/arabia.webp",
    nationality: "unknown",
    chapter: "Stardust Crusaders",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "45",
    name: "Mannish Boy",
    animeDebut: 45,
    image: "https://jojos-bizarre-api.netlify.app/assets/mannish.png",
    nationality: "Egyptian",
    chapter: "Stardust Crusaders",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "46",
    name: "Cameo",
    animeDebut: 48,
    image: "https://jojos-bizarre-api.netlify.app/assets/cameo.webp",
    nationality: "unknown",
    chapter: "Stardust Crusaders",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "47",
    name: "Midler",
    animeDebut: 49,
    image: "https://jojos-bizarre-api.netlify.app/assets/midler.webp",
    nationality: "unknown",
    chapter: "Stardust Crusaders",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "female",
  },
  {
    id: "48",
    name: "Josuke Higashikata",
    animeDebut: 75,
    image: "https://jojos-bizarre-api.netlify.app/assets/josuke.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "49",
    name: "Tomoko Higashikata",
    animeDebut: 75,
    image: "https://jojos-bizarre-api.netlify.app/assets/tomoko.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: false,
    gender: "female",
  },
  {
    id: "50",
    name: "Okuyasu Nijimura",
    animeDebut: 77,
    image: "https://jojos-bizarre-api.netlify.app/assets/okuyasu.webp",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "51",
    name: "Keicho Nijimura",
    animeDebut: 77,
    image: "https://jojos-bizarre-api.netlify.app/assets/keicho.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "52",
    name: "Nijimura's Father",
    animeDebut: 79,
    image: "https://jojos-bizarre-api.netlify.app/assets/father.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: false,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "53",
    name: "Koichi Hirose",
    animeDebut: 75,
    image: "https://jojos-bizarre-api.netlify.app/assets/koichi.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "54",
    name: "Rohan Kishibe",
    animeDebut: 88,
    image: "https://jojos-bizarre-api.netlify.app/assets/rohan.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "55",
    name: "Reimi Sugimoto",
    animeDebut: 91,
    image: "https://jojos-bizarre-api.netlify.app/assets/reimi.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: false,
    isHuman: false,
    isStandUser: false,
    gender: "female",
  },
  {
    id: "56",
    name: "Shigekiyo Yangu",
    animeDebut: 92,
    image: "https://jojos-bizarre-api.netlify.app/assets/shigechi.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "57",
    name: "Mikitaka Hazekura",
    animeDebut: 101,
    image: "https://jojos-bizarre-api.netlify.app/assets/mikitaka.png",
    nationality: "unknown",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: false,
    isStandUser: false,
    gender: "male",
  },
  {
    id: "58",
    name: "Yukako Yamagishi",
    animeDebut: 81,
    image: "https://jojos-bizarre-api.netlify.app/assets/yukako.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "female",
  },
  {
    id: "59",
    name: "Yuya Fungami",
    animeDebut: 103,
    image: "https://jojos-bizarre-api.netlify.app/assets/yuya.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "60",
    name: "Toshikazu Hazamada",
    animeDebut: 81,
    image: "https://jojos-bizarre-api.netlify.app/assets/toshikazu.jpg",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "61",
    name: "Tonio Trussardi",
    animeDebut: 84,
    image: "https://jojos-bizarre-api.netlify.app/assets/tonio.png",
    nationality: "Italian",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "62",
    name: "Aya Tsuji",
    animeDebut: 94,
    image: "https://jojos-bizarre-api.netlify.app/assets/aya.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "female",
  },
  {
    id: "63",
    name: "Yoshikage Kira",
    animeDebut: 91,
    image: "https://jojos-bizarre-api.netlify.app/assets/kira.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "64",
    name: "Yoshihiro Kira",
    animeDebut: 99,
    image: "https://jojos-bizarre-api.netlify.app/assets/yoshihorokira.webp",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: false,
    isHuman: false,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "65",
    name: "Tama (Stray cat)",
    animeDebut: 103,
    image: "https://jojos-bizarre-api.netlify.app/assets/tama.png",
    nationality: "unknown",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: false,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "66",
    name: "Akira Otoishi",
    animeDebut: 86,
    image: "https://jojos-bizarre-api.netlify.app/assets/akira.webp",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "67",
    name: 'Anjuro "Angelo" Katagiri',
    animeDebut: 74,
    image: "https://jojos-bizarre-api.netlify.app/assets/angelo.webp",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "68",
    name: "Bug-Eaten",
    animeDebut: 90,
    image: "https://jojos-bizarre-api.netlify.app/assets/bugeaten.png",
    nationality: "unknown",
    chapter: "Diamond is Unbreakable",
    living: false,
    isHuman: false,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "69",
    name: "Ken Oyanagi",
    animeDebut: 100,
    image: "https://jojos-bizarre-api.netlify.app/assets/ken.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "70",
    name: "Toyohiro Kanedaichi",
    animeDebut: 105,
    image: "https://jojos-bizarre-api.netlify.app/assets/toyohiro.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "71",
    name: "Terunosuke Miyamoto",
    animeDebut: 106,
    image: "https://jojos-bizarre-api.netlify.app/assets/miyamoto.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: false,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "72",
    name: "Masazo Kinoto",
    animeDebut: 105,
    image: "https://jojos-bizarre-api.netlify.app/assets/masazo.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "73",
    name: "Tamami Kobayashi",
    animeDebut: 80,
    image: "https://jojos-bizarre-api.netlify.app/assets/tamami.png",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "74",
    name: "Shizuka Joestar",
    animeDebut: 87,
    image: "https://jojos-bizarre-api.netlify.app/assets/shizuka.webp",
    nationality: "Japanese",
    chapter: "Diamond is Unbreakable",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "female",
  },
  {
    id: "75",
    name: "Giorno Giovanna",
    animeDebut: 114,
    image: "https://jojos-bizarre-api.netlify.app/assets/giorno.png",
    nationality: "Japanese-British",
    chapter: "Vento Aureo",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "76",
    name: "Bruno Bucciarati",
    animeDebut: 114,
    image: "https://jojos-bizarre-api.netlify.app/assets/bucciarati.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "77",
    name: "Leone Abbacchio",
    animeDebut: 117,
    image: "https://jojos-bizarre-api.netlify.app/assets/abbacchio.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "78",
    name: "Guido Mista",
    animeDebut: 117,
    image: "https://jojos-bizarre-api.netlify.app/assets/guido.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "79",
    name: "Narancia Ghirga",
    animeDebut: 117,
    image: "https://jojos-bizarre-api.netlify.app/assets/narancia.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "80",
    name: "Pannacotta Fugo",
    animeDebut: 117,
    image: "https://jojos-bizarre-api.netlify.app/assets/fugo.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "81",
    name: "Trish Una",
    animeDebut: 122,
    image: "https://jojos-bizarre-api.netlify.app/assets/trish.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "female",
  },
  {
    id: "83",
    name: "Coco Jumbo",
    animeDebut: 127,
    image: "https://jojos-bizarre-api.netlify.app/assets/coco.png",
    nationality: "unknown",
    chapter: "Vento Aureo",
    living: true,
    isHuman: false,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "84",
    name: "Diavolo",
    animeDebut: 131,
    image: "https://jojos-bizarre-api.netlify.app/assets/diavolo.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "85",
    name: "Vinegar Doppio",
    animeDebut: 134,
    image: "https://jojos-bizarre-api.netlify.app/assets/doppio.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "86",
    name: "Squalo and Tiziano",
    animeDebut: 135,
    image: "https://jojos-bizarre-api.netlify.app/assets/squalo.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "87",
    name: "Carne",
    animeDebut: 137,
    image: "https://jojos-bizarre-api.netlify.app/assets/carne.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "88",
    name: "Cioccolata",
    animeDebut: 142,
    image: "https://jojos-bizarre-api.netlify.app/assets/ciocco.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "89",
    name: "Secco",
    animeDebut: 142,
    image: "https://jojos-bizarre-api.netlify.app/assets/secco.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "90",
    name: "Polpo",
    animeDebut: 116,
    image: "https://jojos-bizarre-api.netlify.app/assets/polpo.webp",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "91",
    name: "Mario Zucchero",
    animeDebut: 118,
    image: "https://jojos-bizarre-api.netlify.app/assets/mario.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "92",
    name: "Sale",
    animeDebut: 118,
    image: "https://jojos-bizarre-api.netlify.app/assets/sale.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "93",
    name: "Risotto Nero",
    animeDebut: 123,
    image: "https://jojos-bizarre-api.netlify.app/assets/risotto.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "94",
    name: "Formaggio",
    animeDebut: 122,
    image: "https://jojos-bizarre-api.netlify.app/assets/formaggio.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "95",
    name: "Illuso",
    animeDebut: 123,
    image: "https://jojos-bizarre-api.netlify.app/assets/illuso.webp",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "96",
    name: "Prosciutto",
    animeDebut: 123,
    image: "https://jojos-bizarre-api.netlify.app/assets/prosciutto.webp",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "97",
    name: "Pesci",
    animeDebut: 123,
    image: "https://jojos-bizarre-api.netlify.app/assets/peschi.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "98",
    name: "Melone",
    animeDebut: 123,
    image: "https://jojos-bizarre-api.netlify.app/assets/melone.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "99",
    name: "Ghiaccio",
    animeDebut: 123,
    image: "https://jojos-bizarre-api.netlify.app/assets/ghiaccio.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "100",
    name: "Scolippi",
    animeDebut: 151,
    image: "https://jojos-bizarre-api.netlify.app/assets/scolippi.png",
    nationality: "Italian",
    chapter: "Vento Aureo",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "101",
    name: "Jolyne Kujo",
    animeDebut: 153,
    image: "https://jojos-bizarre-api.netlify.app/assets/jolyne.webp",
    nationality: "Japanese-American",
    chapter: "Stone Ocean",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "female",
  },
  {
    id: "102",
    name: "Ermes Costello",
    animeDebut: 153,
    image: "https://jojos-bizarre-api.netlify.app/assets/ermes.webp",
    nationality: "Mexican-American",
    chapter: "Stone Ocean",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "female",
  },
  {
    id: "103",
    name: "Emporio Alniño",
    animeDebut: 155,
    image: "https://jojos-bizarre-api.netlify.app/assets/emporio.png",
    nationality: "American",
    chapter: "Stone Ocean",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "104",
    name: "Foo Fighters (F.F.)",
    animeDebut: 159,
    image: "https://jojos-bizarre-api.netlify.app/assets/foofighters.png",
    nationality: "none",
    chapter: "Stone Ocean",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "female",
  },
  {
    id: "105",
    name: "Narciso Anasui",
    animeDebut: 162,
    image: "https://jojos-bizarre-api.netlify.app/assets/narciso.png",
    nationality: "unknown",
    chapter: "Stone Ocean",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "106",
    name: "Weather Report",
    animeDebut: 162,
    image: "https://jojos-bizarre-api.netlify.app/assets/weather.png",
    nationality: "Italian,American",
    chapter: "Stone Ocean",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "107",
    name: "Gwess",
    animeDebut: 153,
    image: "https://jojos-bizarre-api.netlify.app/assets/gwess.webp",
    nationality: "American",
    chapter: "Stone Ocean",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "female",
  },
  {
    id: "108",
    name: "Enrico Pucci",
    animeDebut: 160,
    image: "https://jojos-bizarre-api.netlify.app/assets/pucci.webp",
    nationality: "Italian-American",
    chapter: "Stone Ocean",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "109",
    name: "Donatello Versus",
    animeDebut: 180,
    image: "https://jojos-bizarre-api.netlify.app/assets/donatello.png",
    nationality: "unknown",
    chapter: "Stone Ocean",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "110",
    name: "Rikiel",
    animeDebut: 177,
    image: "https://jojos-bizarre-api.netlify.app/assets/rikiel.webp",
    nationality: "unknown",
    chapter: "Stone Ocean",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "111",
    name: "Ungalo",
    animeDebut: 177,
    image: "https://jojos-bizarre-api.netlify.app/assets/ungalo.png",
    nationality: "unknown",
    chapter: "Stone Ocean",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "112",
    name: "The Green Baby",
    animeDebut: 171,
    image: "https://jojos-bizarre-api.netlify.app/assets/greenbaby.png",
    nationality: "unknown",
    chapter: "Stone Ocean",
    living: false,
    isHuman: false,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "113",
    name: "Johngalli A",
    animeDebut: 155,
    image: "https://jojos-bizarre-api.netlify.app/assets/johngalli.png",
    nationality: "unknown",
    chapter: "Stone Ocean",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "114",
    name: "Sports Maxx",
    animeDebut: 164,
    image: "https://jojos-bizarre-api.netlify.app/assets/sportsmaxx.png",
    nationality: "American",
    chapter: "Stone Ocean",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "115",
    name: "Miuccia Miuller",
    animeDebut: 175,
    image: "https://jojos-bizarre-api.netlify.app/assets/miucca.png",
    nationality: "American",
    chapter: "Stone Ocean",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "female",
  },
  {
    id: "116",
    name: "Miraschon",
    animeDebut: 161,
    image: "https://jojos-bizarre-api.netlify.app/assets/miraschon.webp",
    nationality: "American",
    chapter: "Stone Ocean",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "female",
  },
  {
    id: "117",
    name: "Lang Rangler",
    animeDebut: 162,
    image: "https://jojos-bizarre-api.netlify.app/assets/lang.png",
    nationality: "American",
    chapter: "Stone Ocean",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "118",
    name: "Kenzou",
    animeDebut: 167,
    image: "https://jojos-bizarre-api.netlify.app/assets/kenzou.png",
    nationality: "unknown",
    chapter: "Stone Ocean",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "119",
    name: "D an G",
    animeDebut: 167,
    image: "https://jojos-bizarre-api.netlify.app/assets/DG.webp",
    nationality: "unknown",
    chapter: "Stone Ocean",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "120",
    name: "Guccio",
    animeDebut: 171,
    image: "https://jojos-bizarre-api.netlify.app/assets/guccio.png",
    nationality: "unknown",
    chapter: "Stone Ocean",
    living: false,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "121",
    name: "Viviano Westwood",
    animeDebut: 165,
    image: "https://jojos-bizarre-api.netlify.app/assets/viviano.webp",
    nationality: "unknown",
    chapter: "Stone Ocean",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
  {
    id: "122",
    name: "Thunder McQueen",
    animeDebut: 158,
    image: "https://jojos-bizarre-api.netlify.app/assets/thunder.webp",
    nationality: "unknown",
    chapter: "Stone Ocean",
    living: true,
    isHuman: true,
    isStandUser: true,
    gender: "male",
  },
];
